### ISSUE TITLE
Current Part 4 Tutorial (Failing to Render)

### ISSUE THREAD

**Issue by h1cks** [mrjfalk/SharpDXTutorials#1]
Have compiled your project locally to find that although displays window, no triangle is rendering.

Sharpdx: Version 3.0

**Comment by h1cks** [comment]
Add

d3dDeviceContext.InputAssembler.PrimitiveTopology = PrimitiveTopology.TriangleList;

after you set the shaders.

on the context call and this fixes the problem

**Comment by h1cks** [comment]
As per comment above.  @mrjfalk

**Comment by mrjfalk** [comment]
Yes, you are correct. For some reason it worked anyway on my desktop PC, but not on my laptop, might be driver specific. It was, as expected, set as "Undefined" on both if reading the value, which is of course bad. Will update code and tutorial. Thanks.

**Comment by h1cks** [comment]
Thanks, also, I have a query on the orientation also.  For some reason my triangle ends up upside down compared to the expected result.  Think this might be orientation that needs to be set also.

**Comment by mrjfalk** [comment]
Are you sure? By intention I set vertices to draw it, what most people would consider, "up-side-down" (point downwards). It should draw with point up-wards if you change vertices array to for example:
`private Vector3[] vertices = new Vector3[] { new Vector3(0.0f, 0.5f, 0.0f), new Vector3(0.5f, -0.5f, 0.0f), new Vector3(-0.5f, -0.5f, 0.0f) };`

**Comment by h1cks** [comment]
Will double check tonight.  

Will also be building from your example for a while to do camera functionality and texturing.  If interested will send the code through (I've refactored to my own project, but will add to your example code)
